FROM openjdk:10.0.2-jdk
# COPY /target/fx-trading-0.0.1-SNAPSHOT.jar /usr/src/myapp
# WORKDIR /usr/src/myappcls
# RUN javac Sample.java
EXPOSE 8210
# CMD ["java", "-jar", "fx-trading-0.0.1-SNAPSHOT.jar"]

ARG JAR_FILE=target/quote-service-0.0.1-SNAPSHOTT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} quote-service.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/quote-service.jar"]
