FROM node:alpine AS builder

WORKDIR /app

COPY . .

RUN npm install && \
    npm run build

FROM nginx:alpine

COPY --from=builder dist/* /usr/share/nginx/html/

COPY --from=builder nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html
