FROM openjdk:10.0.2-jdk
# COPY /target/fx-trading-0.0.1-SNAPSHOT.jar /usr/src/myapp
# WORKDIR /usr/src/myappcls
# RUN javac Sample.java
EXPOSE 8210
# CMD ["java", "-jar", "fx-trading-0.0.1-SNAPSHOT.jar"]

ARG JAR_FILE=target/fx-trading-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} fx-trading.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/fx-trading.jar"]

# # Stage 1 (to create a "build" image, ~140MB)
# FROM openjdk:8-jdk-alpine3.7 AS builder
# RUN java -version

# COPY . /usr/src/myapp/
# WORKDIR /usr/src/myapp/
# RUN apk --no-cache add maven && mvn --version
# RUN mvn package

# # Stage 2 (to create a downsized "container executable", ~87MB)
# FROM openjdk:8-jre-alpine3.7
# WORKDIR /root/
# COPY --from=builder /usr/src/myapp/target/app.jar .

# EXPOSE 8123
# ENTRYPOINT ["java", "-jar", "./app.jar"]

